name: Build Dinosaur-Exploder

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            classifier: linux
            suffix: linux
          - os: windows-latest
            classifier: win
            suffix: windows
          - os: macos-latest
            classifier: mac
            suffix: macos

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean javafx:jlink -Djavafx.platform=${{ matrix.classifier }}

      - name: Zip JLink output
        run: zip -r fxgl-dino-${{ matrix.suffix }}.zip game/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fxgl-dino-${{ matrix.suffix }}
          path: fxgl-dino-${{ matrix.suffix }}.zip
