name: Upload JAR Artifact on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win

    name: Build for ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Rename and zip artifact
        run: |
          mkdir output
          cp target/dinosaur-exploder-1.0.jar output/Dinosaur-Exploder-${{ matrix.platform }}.jar
          cd output && zip Dinosaur-Exploder-${{ matrix.platform }}.zip Dinosaur-Exploder-${{ matrix.platform }}.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dinosaur-Exploder-${{ matrix.platform }}
          path: output/Dinosaur-Exploder-${{ matrix.platform }}.zip
