name: Publish artifacts on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win

    name: Build for ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Rename JAR with platform
        run: |
          mkdir -p output
          cp target/*.jar output/Dinosaur-Exploder-${{ matrix.platform }}.jar

      - name: Upload platform-specific JAR
        uses: actions/upload-artifact@v4
        with:
          name: dinosaur-exploder-${{ matrix.platform }}
          path: output/Dinosaur-Exploder-${{ matrix.platform }}.jar

  publish:
    name: Publish All JARs to GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-jars

      - name: Display artifacts structure
        run: ls -R ./release-jars

      - name: Publish JARs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release-jars/**/*.jar
